(function() {
  
	Backbone.spriteSheetDefinitions = [{
    id: "miam",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 0,
    y: 0,
    tileWidth: 180,
    tileHeight: 180,
    tileColumns: 4,
    tileRows: 1
  }, {
    id: "miam2",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 0,
    y: 360,
    tileWidth: 180,
    tileHeight: 180,
    tileColumns: 4,
    tileRows: 1
  }, {
    id: "garfield",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 0,
    y: 720,
    tileWidth: 180,
    tileHeight: 180,
    tileColumns: 4,
    tileRows: 1
  }, {
    id: "fruits",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 0,
    y: 270,
    tileWidth: 90,
    tileHeight: 90,
    tileColumns: 8,
    tileRows: 1
  }, {
    id: "bomb",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 450,
    y: 180,
    tileWidth: 90,
    tileHeight: 90,
    tileColumns: 1,
    tileRows: 1
  }, {
    id: "cupcake",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 540,
    y: 180,
    tileWidth: 90,
    tileHeight: 90,
    tileColumns: 1,
    tileRows: 1
  }, {
    id: "boom",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 540,
    y: 540,
    tileWidth: 160,
    tileHeight: 90,
    tileColumns: 1,
    tileRows: 1
  }, {
    id: "splat",
    img: "#miam",
    imgUrl: "img/miam.png",
    x: 0,
    y: 180,
    tileWidth: 90,
    tileHeight: 90,
    tileColumns: 5,
    tileRows: 1
  }];

}).call(this);